# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.8
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12+de.tu_darmstadt.seemoo.nfcgate.network.auth\"\x1e\n\rAuthChallenge\x12\r\n\x05nonce\x18\x01 \x01(\t\"/\n\x0c\x41uthResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0c\n\x04hmac\x18\x02 \x01(\t\"A\n\nAuthResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTHCHALLENGE']._serialized_start=59
  _globals['_AUTHCHALLENGE']._serialized_end=89
  _globals['_AUTHRESPONSE']._serialized_start=91
  _globals['_AUTHRESPONSE']._serialized_end=138
  _globals['_AUTHRESULT']._serialized_start=140
  _globals['_AUTHRESULT']._serialized_end=205
# @@protoc_insertion_point(module_scope)
